### ISSUE TITLE
log4j.xml URI 관련 에러 질문 사항

### ISSUE THREAD

**Issue by woo-chang** [gusah009/keeper_spring_study#5]
<img width="867" alt="스크린샷 2021-09-23 오후 12 46 41" src="https://user-images.githubusercontent.com/78212016/134451940-09e03a72-8f36-43b3-9161-f61b9e2bf0fb.png">

`log4jdbc-log4j2` 라이브러리를 사용하며 로그의 레벨을 설정하기 위해 `log4j.xml` 파일 작성 도중 다음과 같은 에러를 발견했습니다.
에러를 수정하기 위해 검색해봤지만 해결하지 못해 다른분들의 의견을 듣고자 공유합니다.

**Comment by gusah009** [comment]
[https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=amabile29&logNo=221197639451](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=amabile29&logNo=221197639451)
위 사이트에 대답이 나와있긴 하네요
저는 저 에러를 무시하고 실행시켰을 때 문제없이 됐었습니다.

**Comment by woo-chang** [comment]
에러를 그대로 두고 진행 하셨을 때
테스트 결과에서 로그 출력에 대해 달라 지는 부분이 있는지 궁금합니다!
저도 에러인 상태로 테스트 실행은 잘되지만 출력에 있어 달라 지는 부분이 없었습니다.

**Comment by gusah009** [comment]
어떤 부분 로그를 말씀하시는지 잘 모르겠긴 한데, log.info()에서 나타나는 부분은 문제없이 잘 나타났었습니다!

**Comment by woo-chang** [comment]
`log4j.xml` 파일이 적용되기 이전에는 p103쪽처럼 로그가 보이고
`log4j.xml` 파일 적용 이후에는 p105쪽처럼 로그가 보여야 하는거 아닌가요??

**Comment by gusah009** [comment]
엇 저도 방금 확인해봤는데 
![image](https://user-images.githubusercontent.com/26597702/134468108-f30b9bee-f7cc-4264-a482-783006238a5e.png)
warn으로 설정을 해줬는데도 INFO로 나오네요....

**Comment by gusah009** [comment]
### 이게 왜 되는진 모르겠지만 
![image](https://user-images.githubusercontent.com/26597702/134474255-bb6c8f13-4de7-4503-a1bf-e6ae9da4f430.png)
```src/test/resources``` 폴더에 log4j.properties로 아래 코드를 넣고 실행시키니까 잘 됩니다
```properties
log4j.properties
log4j.rootLogger=INFO, stdout

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern= %-5p [%c{1}:%L] - %m%n
```

**Comment by woo-chang** [comment]
감사합니다!!
